"""Subsystem 7b: compiling the assembled tree to SMV for nuXmv.

Design doc: ``survey/design/07_safety_cbf_formal_verification.md`` sec 1.2.

nuXmv is external and licence-gated, so nothing in this project depends on it.
This emits the model so the path stays open, and ``src/flow2bt/falsify.py``
provides evidence that runs today.

What is and is not modelled
---------------------------
The tree's *control flow* translates exactly: Sequence and Fallback are
deterministic given the guard values, and each guard is a linear predicate over
the feature vector, so the whole tick is a boolean function of
``len(FEATURE_NAMES)`` real inputs.

What does not translate is everything continuous -- the DMP integration, the
CBF-QP, the agent dynamics. Model checking this file proves properties of the
*decision logic* ("the tree can never select MarchStraight while
IsCollisionImminent holds"), not of the closed loop. Design 07 sec 1.2 states
the specs as ``G !(distance < 0.7)``, which is a property of the closed loop and
is **not** established by checking this model. Saying otherwise would be the
single easiest way to overclaim in this project, so the emitted file carries
that caveat in a comment and ``LTLSPEC`` lines are emitted only for properties
that are actually about the tree.
"""

from __future__ import annotations

from typing import Sequence

from src.flow2bt.assembly import AssembledTree
from src.flow2bt.bt import Action, Condition, Fallback, Node, Sequence as SequenceNode

HEADER = """-- Generated by src/flow2bt/verification.py
--
-- SCOPE: this models the Behavior Tree's DECISION LOGIC only. The DMP
-- integration, the CBF-QP and the agent dynamics are not represented, so
-- properties proved here are about which action the tree selects, NOT about
-- closed-loop collision freedom. Design 07 sec 1.2 writes
-- `LTLSPEC G !(distance_to_nearest_agent < 0.7)`; that is a closed-loop
-- property and is NOT established by checking this file. Collision freedom is
-- argued from the barrier's forward invariance and measured by
-- src/flow2bt/falsify.py.
--
-- Guards are free boolean inputs here. Each corresponds to a linear predicate
-- w . phi(s) + b >= 0 over the feature vector; the mapping is listed below so
-- a counterexample assignment can be read back into physical units.
"""


def _sanitise(name: str) -> str:
    return "".join(character if character.isalnum() else "_" for character in name)


def _expr(node: Node, leaf_variable: str) -> str:
    """Nested case expression giving the selected leaf index."""
    if isinstance(node, Action):
        return str(node.leaf_index)
    if isinstance(node, Condition):
        return _sanitise(node.name)
    if isinstance(node, SequenceNode):
        # Sequence(guard, subtree): the subtree runs iff the guard holds.
        guards = [c for c in node.children if isinstance(c, Condition)]
        others = [c for c in node.children if not isinstance(c, Condition)]
        condition = " & ".join(_sanitise(g.name) for g in guards) or "TRUE"
        inner = _expr(others[0], leaf_variable) if others else "-1"
        return f"({condition} ? {inner} : -1)"
    if isinstance(node, Fallback):
        expression = "-1"
        for child in reversed(node.children):
            child_expression = _expr(child, leaf_variable)
            expression = f"(({child_expression}) != -1 ? ({child_expression}) : {expression})"
        return expression
    raise TypeError(f"cannot translate {type(node).__name__}")


def to_smv(tree: AssembledTree, module_name: str = "main") -> str:
    """Emit an SMV module for the assembled tree."""
    from src.flow2bt.bt import action_leaves, condition_nodes

    conditions = condition_nodes(tree.root)
    leaves = action_leaves(tree.root)

    lines = [HEADER, ""]
    for guard in tree.guards:
        terms = " ".join(
            f"{weight:+.6g}*{name}"
            for name, weight in zip(guard.feature_names, guard.weights)
            if abs(weight) > 1e-9
        )
        lines.append(f"-- {_sanitise(guard.name)} :=  {terms} {guard.bias:+.6g} >= 0")
        lines.append(f"--   cross-validated accuracy {guard.accuracy:.3f}"
                     + ("  [WEAK: not decidable from observable state]" if guard.is_weak else ""))
    lines += ["", f"MODULE {module_name}", "VAR"]
    for condition in conditions:
        lines.append(f"  {_sanitise(condition.name)} : boolean;")
    lines.append(f"  leaf : -1..{max((leaf.leaf_index for leaf in leaves), default=0)};")
    lines += ["", "ASSIGN", f"  leaf := {_expr(tree.root, 'leaf')};", ""]

    # Only properties that are genuinely about the tree.
    lines += [
        "-- Totality: the tree always selects some action. This one IS about the",
        "-- tree, and is the property src/flow2bt/assembly.py argues structurally.",
        "LTLSPEC G (leaf >= 0)",
        "",
    ]
    for leaf in leaves:
        lines.append(f"-- reachability of {leaf.name}")
        lines.append(f"CTLSPEC EF (leaf = {leaf.leaf_index})")
    return "\n".join(lines) + "\n"


def write_smv(tree: AssembledTree, path) -> None:
    from pathlib import Path

    Path(path).write_text(to_smv(tree))
